token="your telegram token"
phone="your contact number"
telega="your telegram username @blablabla"
address="your office address"
google_link="link to your office position on the map"

gel_price="price"
extension_price="price"
simple_price="price"
telega_id="your telegram id"